### ISSUE TITLE
Issues Mercado-Liebre

### ISSUE THREAD

**Issue by Florsecco** [lucianafigue/mercadoLiebreRender#1]
- [] 1-Cumple
- [] 2-Cumple
- [] 3-Cumpletambien
- [] 4-Cumple
- [] 5-Cumple
- [] 6-Cumple
- [] 7-Cumple
- [] 8-Cumple
- [] 9- Me parece muy acertadas las transiciones y las animaciones realizadas, también las adaptaciones a los distintos tamaños de pantalla son muy eficaces y por ultimo el cambio en el footer en la vista login queda muy estético.
- [] 10-Lo único que considero que se podría mejorar (ya para ser muy perfeccionista) es que quizás en la resolución mas grande de pantalla achicaría un poco el logo, y sacaría el estilo que se le agrega a los links de Crea tu cuenta e Ingresa. Después esta todo perfecto
![image](https://github.com/lucianafigue/mercadoLiebreRender/assets/146774903/3699c505-8627-42e0-8a70-983866be87f1)

**Comment by lucianafigueroa** [comment]
Muchas gracias por las recomendaciones Flor! Ya hice todo, si quieres puedes verlo desde aquí https://luciana-proyectodh.onrender.com ya que cambié el link.
