### ISSUE TITLE
revision MercadoLiebre #1

### ISSUE THREAD

**Issue by decimechochi** [lucianafigue/mercadoLiebreRender#2]
punto 2 - cumple solo  le falta el margen inferior de 10px. o al menos no lo vi en los estilos al inspeccionar.

Que buen trabajo Lu! te felicito.

**Comment by decimechochi** [comment]
El punto 2 tenia correcto lo que se pidio en margenes y tamaño. No lo habia leido bien perdon.

Todos los demas puntos cumplen tal como se dicta la consigna.

**Comment by lucianafigueroa** [comment]
Muchas gracias Ro! Felicitaciones a vos también por tu esfuerzo, seguí así!
